### ISSUE TITLE
Default us-west-1 AMI missing Docker

### ISSUE THREAD

**Issue by jfenc91** [mbabineau/cloudformation-mesos#5] opened 2015-04-19 21:56 UTC
Nice script! But I think your new ami for us-west-1, ami-1d48aa59, is missing docker. The old one, ami-b9799ffd, seems to work fine though.

**Comment by mbabineau** [comment] 2015-04-19 22:26
Fixed with 1c74393. Root cause was a copy-paste error, my bad.

Thanks for reporting!

**Closed as completed by mbabineau** 2015-04-19 22:26 UTC
